In [2]:
import pandas as pd 
import xlrd
from xlrd import open_workbook

In [3]:
xls = pd.ExcelFile('D:\CPEG\data_2\TCPGE_data.xlsx')

In [4]:
xls.sheet_names

['X', 'Y', 'Z', 'XY', 'XZ', 'YZ', 'XYZ', 'Sheet2']

In [5]:
data_x = pd.read_excel(xls, sheet_name="X")

In [6]:
data_x

,X,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,D=(a'-a)/a,-0.030000,-0.029000,-0.028000,-0.027000,-0.026000,-0.025000,-0.024000,-0.023000,-0.022000,...,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000,-0.009000
1,v^t_x,0.766192,0.760761,0.754821,0.743964,0.742577,0.736063,0.728230,0.716366,0.709921,...,0.226443,0.213820,0.194877,0.182749,0.166392,0.158694,0.139219,0.127145,0.112860,0.106340
2,v^t_y,0.609807,0.605057,0.599857,0.603324,0.592645,0.591795,0.586697,0.589650,0.584429,...,0.371487,0.368831,0.368160,0.364951,0.357727,0.356955,0.358533,0.350896,0.345545,0.344869
3,v^t_z,-0.314216,-0.314882,-0.313587,-0.333691,-0.330207,-0.334714,-0.332462,-0.338710,-0.337228,...,-0.353257,-0.356614,-0.360506,-0.363490,-0.358646,-0.368256,-0.370789,-0.364718,-0.362217,-0.370333
4,v_x,0.694818,0.694070,0.694740,0.716945,0.711458,0.716928,0.713111,0.723716,0.718392,...,0.643091,0.640394,0.633943,0.629969,0.609832,0.623677,0.604089,0.579888,0.556534,0.566278
5,v_y,0.545896,0.546730,0.545951,0.540711,0.541798,0.540291,0.540372,0.539274,0.540819,...,-0.447361,-0.444552,-0.439495,-0.437315,-0.431830,-0.434097,-0.424419,-0.419106,-0.413418,-0.415093
6,v_z,-0.526147,0.522549,0.524165,0.533857,0.536454,0.542094,0.542911,0.550250,0.549183,...,0.679253,0.684323,0.696284,0.702288,0.715166,0.713157,0.732926,0.746261,0.758547,0.756978
7,d_x,-5.542581,-4.169244,-2.738580,-2.252581,-0.912202,-0.114594,0.038749,0.270635,-0.140952,...,3.632217,4.161957,4.073500,4.538562,4.472886,5.120755,5.408988,5.543545,6.478669,6.533691
8,d_y,3.224761,1.738236,-0.223565,1.644895,-0.823094,-1.271277,-1.430777,-1.955426,-1.471823,...,0.463643,0.783479,0.617034,0.658794,0.022732,0.239559,0.547654,0.064611,0.540009,0.046288
9,d_z,-0.568188,-0.244564,-1.643217,3.130360,0.453258,1.046778,0.790910,0.559670,0.668129,...,-1.458443,-1.688859,-1.283180,-1.211490,-0.668805,-0.656017,-0.412630,0.163030,-0.151462,0.386903
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,B^t_xy,0.054874,0.054499,0.054618,0.055871,0.055537,0.055901,0.055624,0.056134,0.055537,...,0.038277,0.036767,0.034452,0.032834,0.031130,0.029452,0.026748,0.025380,0.023275,0.021776
12,B^t_yx,0.033872,0.033817,0.033728,0.031779,0.032208,0.031749,0.031940,0.031168,0.031475,...,0.018523,0.017718,0.016558,0.015822,0.015610,0.014268,0.013203,0.013257,0.012843,0.011700

In [9]:
data_x["Unnamed: 1"][0]

-0.03

In [20]:
data_x.shape[1]

62

In [23]:
for i in range(data_x.shape[0]):
    val = [] 
    for j in range(data_x.shape[1]):
        print(data_x.value)

AttributeError: 'DataFrame' object has no attribute 'value'